CREATE TABLE restaurant (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    nit VARCHAR(50) NOT NULL UNIQUE,
    address VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    url_logo VARCHAR(255) NOT NULL,
    id_owner BIGINT NOT NULL
);